INSERT INTO 
	movimentos
	(
	FormaDePagamento,
	CADASTRO_CATEGORIA,
	controle,
	CADASTRO_USUARIO,
	CADASTRO_EMISSAO
	)

SELECT 
	CONDICAO_PAGAMENTO,
	CADASTRO_CATEGORIA,
	CONDICAO,
	CAD_USUARIO, 
	CAD_EMISSAO 
FROM 
	vw_mov_condicoes 
WHERE 
	CADASTRO_CATEGORIA = 'MOV_CONDICAO';