ALTER TABLE servicos 

ADD CADASTRO_TIPO VARCHAR(2) NULL DEFAULT NULL COMMENT 'TIPO: PJ - PESSOA JURIDICA ; PF - PESSOA FISICA',
ADD COBRANCA_INSCRICAO VARCHAR(14) NULL DEFAULT NULL COMMENT 'NUMERO DE INSCRICAO DO SACADO (CNPJ/CPF)',

ADD COBRANCA_SACADO VARCHAR(30) NULL DEFAULT NULL COMMENT 'NOME DO SACADO',
ADD COBRANCA_LOGRADOURO VARCHAR(40) NULL DEFAULT NULL COMMENT 'LOGRADOURO',
ADD COBRANCA_BAIRRO VARCHAR(12) NULL DEFAULT NULL COMMENT 'COBRANÇA - BAIRRO',
ADD COBRANCA_CEP VARCHAR(8) NULL DEFAULT NULL COMMENT 'COBRANÇA - CEP',
ADD COBRANCA_CIDADE VARCHAR(15) NULL DEFAULT NULL COMMENT 'COBRANÇA - CIDADE',
ADD COBRANCA_ESTADO VARCHAR(2) NULL DEFAULT NULL COMMENT 'COBRANÇA - ESTADO',

ADD COBRANCA_CONTATO VARCHAR(15) NULL DEFAULT NULL COMMENT 'COBRANÇA - CONTATO',
ADD COBRANCA_TELEFONE VARCHAR(50) NULL DEFAULT NULL COMMENT 'COBRANÇA - TELEFONE',
ADD COBRANCA_EMAIL VARCHAR(120) NULL DEFAULT NULL COMMENT 'COBRANÇA - E-MAIL',

ADD CONTRATO_PERIODO_LOCACAO INT(11) NULL DEFAULT NULL COMMENT 'CONTRATO - PERIODO DE LOCAÇÃO',
ADD CONTRATO_FORMA_PAGAMENTO VARCHAR(50) NULL DEFAULT NULL COMMENT 'CONTRATO - FORMA DE PAGAMENTO',
ADD CONTRATO_FATURAMENTO_DIAS INT(10) NULL DEFAULT NULL COMMENT 'CONTRATO - DIAS PARA FATURAMENTO',
ADD CONTRATO_RETIRADA_AUTOMATICA INT(11) NULL DEFAULT NULL COMMENT 'CONTRATO - RETIRADA AUTOMATICA',
ADD CONTRATO_VCTO_APOS_ENTREGA INT(11) NULL DEFAULT NULL COMMENT 'CONTRATO - VENCIMENTO APOS A ENTREGA',

ADD CONTRATO_VALOR DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'CONTRATO - VALOR',
ADD CONTRATO_MULTA_MORA DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'CONTRATO - MULTA DE MORA',
ADD CONTRATO_MULTA_DIA DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'CONTRATO - MULTA POR DIA',
ADD CONTRATO_NF TINYINT(1) NULL DEFAULT '0' COMMENT 'CONTRATO - EMISSÃO DE NF',
ADD CONTRATO_ISS TINYINT(1) NULL DEFAULT '0' COMMENT 'CONTRATO - EMISSÃO DE ISS',
ADD CONTRATO_CTR TINYINT(1) NULL DEFAULT '0' COMMENT 'CONTRATO - EMISSÃO DE CTR';
