CALL `sp_ADM_SISTEMA_CATEGORIA_INSERT`('usuarios', 'adm');
CALL `sp_ADM_SISTEMA_CATEGORIA_INSERT`('departamentos', 'adm');
CALL `sp_ADM_SISTEMA_CATEGORIA_INSERT`('operacoes', 'adm');
CALL `sp_ADM_SISTEMA_CATEGORIA_INSERT`('funcoes', 'adm');

CALL `sp_ADM_SISTEMA_USUARIO_INSERT`('atendente','RETEC', 'adm');
CALL `sp_ADM_SISTEMA_USUARIO_INSERT`('logistica','RETEC', 'adm');
CALL `sp_ADM_SISTEMA_USUARIO_INSERT`('cobranca','RETEC', 'adm');
CALL `sp_ADM_SISTEMA_USUARIO_INSERT`('financeiro','RETEC', 'adm');
CALL `sp_ADM_SISTEMA_USUARIO_INSERT`('gerente','RETEC', 'adm');
CALL `sp_ADM_SISTEMA_USUARIO_INSERT`('adm','RETEC', 'adm');

CALL `sp_ADM_SISTEMA_DEPARTAMENTO_INSERT`('atendimento', 'adm');
CALL `sp_ADM_SISTEMA_DEPARTAMENTO_INSERT`('logistica', 'adm');
CALL `sp_ADM_SISTEMA_DEPARTAMENTO_INSERT`('cobranca', 'adm');
CALL `sp_ADM_SISTEMA_DEPARTAMENTO_INSERT`('financeiro', 'adm');
CALL `sp_ADM_SISTEMA_DEPARTAMENTO_INSERT`('administracao', 'adm');
CALL `sp_ADM_SISTEMA_DEPARTAMENTO_INSERT`('sistema', 'adm');

CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('AGENDA DE SOLICITAÇÕES','btnAGENDA', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('CADASTRO DE SOLICITAÇÃO','btnSOLICITACAO', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('CADASTRO DE CLIENTES','btnCLIENTES', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('TELEFONES UTEIS','btnTELEFONES_UTEIS', 'adm');

CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('CONTROLE DE ROTEIROS','btnROTEIROS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('CONTROLE DE VIAGENS','btnVIAGENS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('ONDE ESTÃO AS CAÇAMBAS?','btnCACAMBAS', 'adm');

CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('FATURAMENTO','btnFATURAMENTO', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('GERAR BOLETOS','btnBOLETOS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('ARQUIVO DE REMESSA','btnREMESSA', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('EMISSÃO DE RECIBOS','btnRECIBOS', 'adm');

CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('MOVIMENTO FINANCEIRO','btnMOVIMENTO', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('RELATÓRIOS FINANCEIROS','btnIMPRESSOS_FINANCEIRO', 'adm');

CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('ADM DE USUÁRIOS','btnADM_USUARIOS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('ADM DE CLIENTES','btnADM_CLIENTES', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('ADM DE FATURAMENTO','btnADM_FATURAMENTO', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('TRANSPORTADOR','btnADM_TRANSPORTADOR', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('VEICULOS','btnADM_VEICULOS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('FUNCIONÁRIOS','btnADM_FUNCIONARIOS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('ATERROS','btnADM_ATERROS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('PROPAGANDAS','btnADM_PROPAGANDAS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('MATERIAIS','btnADM_MATERIAIS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('LINKS','btnADM_LINKS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('TELEFONES UTEIS','btnADM_TELEFONES_UTEIS', 'adm');

CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('USUÁRIOS','btnUSUARIOS', 'adm');
CALL `sp_ADM_SISTEMA_OPERACAO_INSERT`('CONTROLE OPERACIONAL','btnCONTROLE_OPERACIONAL', 'adm');

CALL `sp_ADM_SISTEMA_FUNCAO_INSERT`('adicionar', 'btnADICIONAR', 'ADM')
CALL `sp_ADM_SISTEMA_FUNCAO_INSERT`('editar', 'btnEDITAR', 'ADM');
CALL `sp_ADM_SISTEMA_FUNCAO_INSERT`('excluir', 'btnEXCLUIR', 'ADM');
CALL `sp_ADM_SISTEMA_FUNCAO_INSERT`('gravar', 'btnGRAVAR', 'ADM');