CREATE TABLE `servicos` (
	-- DADOS
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ID_RELACAO` INT(11) NULL DEFAULT '0' COMMENT 'RELACIONAMENTO',
	`ID_CADASTRO` INT(11) NULL DEFAULT NULL COMMENT 'CLIENTE OU MOTORISTA',
	`ID_OBRA` INT(11) NULL DEFAULT NULL COMMENT 'OBRA',
	`ID_SOLICITANTE` INT(11) NULL DEFAULT NULL COMMENT 'CONTATO',
	
	-- ORDEM	
	`VIAGEM` INT(11) NULL DEFAULT NULL COMMENT 'ORDEM DA VIAGEM',
	`ORDEM` INT(11) NULL DEFAULT NULL COMMENT 'ORDEM DA TAREFA',
	
	-- LIGAÇÃO, ROTEIRO, VIAGEM
	`COLOCA` INT(11) NULL DEFAULT '0' COMMENT 'COLOCA',
	`TROCA` INT(11) NULL DEFAULT '0' COMMENT 'TROCA',
	`RETIRA` INT(11) NULL DEFAULT '0' COMMENT 'RETIRA',
	`DT_COLOCA` DATE NULL DEFAULT NULL COMMENT 'DATA DA TAREFA',
	`DT_TROCA` DATE NULL DEFAULT NULL COMMENT 'DATA DA TAREFA',
	`DT_RETIRA` DATE NULL DEFAULT NULL COMMENT 'DATA DA TAREFA',
	`PR_COLOCA` TINYINT(1) NULL DEFAULT '0' COMMENT 'PRIORIDADE : 0 - NORMAL ; 1 - ALTA',
	`PR_TROCA` TINYINT(1) NULL DEFAULT '0' COMMENT 'PRIORIDADE : 0 - NORMAL ; 1 - ALTA',
	`PR_RETIRA` TINYINT(1) NULL DEFAULT '0' COMMENT 'PRIORIDADE : 0 - NORMAL ; 1 - ALTA',
	`SERVICO_MATERIAL` VARCHAR(255) NULL DEFAULT NULL COMMENT 'MATERIAL',
	`SERVICO_OBSERVACAO` VARCHAR(255) NULL DEFAULT NULL COMMENT 'OBSERVAÇÃO',
	`SERVICO_VALOR` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'VALOR DO SERVICO',
	
	-- CONTROLE
	`SERVICO_EMISSAO` DATE NULL DEFAULT NULL COMMENT 'DATA DE EMISSÃO',
	`SERVICO_INICIO` TIME NULL DEFAULT NULL COMMENT 'HORA DE INICIO',
	`SERVICO_TERMINIO` TIME NULL DEFAULT NULL COMMENT 'HORA DE TERMINIO',
	`SERVICO_CATEGORIA` VARCHAR(50) NULL DEFAULT NULL COMMENT 'LIGAÇÃO, ROTEIRO, VIAGEM',
	`SERVICO_STATUS` TINYINT(1) NULL DEFAULT '0' COMMENT 'STATUS: 0 - Ñ, OK ; 1 - OK',
	
	--  SOBRE
	`SERVICO_NOME` VARCHAR(255) NULL DEFAULT NULL COMMENT 'CLIENTE OU MOTORISTA',
	`SERVICO_CONTATO` VARCHAR(100) NULL DEFAULT NULL COMMENT 'PRINCIPAL - CONTATO RESPONSÁVEL',
	`SERVICO_TELEFONE` VARCHAR(100) NULL DEFAULT NULL COMMENT 'PRINCIPAL - TELEFONE',
	`SERVICO_EMAIL` VARCHAR(120) NULL DEFAULT NULL COMMENT 'PRINCIPAL - EMAIL',
	
	-- SOLICITANTE
	`SERVICO_SOLICITANTE` VARCHAR(100) NULL DEFAULT NULL COMMENT 'SOLICITANTE',
	`SERVICO_SOLICITANTE_TELEFONE` VARCHAR(100) NULL DEFAULT NULL COMMENT 'SOLICITANTE - TELEFONE',
	`SERVICO_SOLICITANTE_EMAIL` VARCHAR(120) NULL DEFAULT NULL COMMENT 'SOLICITANTE - E-MAIL',
	
	-- OBRA
	`SERVICO_OBRA` VARCHAR(255) NULL DEFAULT NULL COMMENT 'OBRA',
	`SERVICO_OBRA_BAIRRO` VARCHAR(50) NULL DEFAULT NULL COMMENT 'OBRA - BAIRRO',
	
	-- COBRANÇA
	`CADASTRO_TIPO` VARCHAR(2) NULL DEFAULT NULL COMMENT 'TIPO: PJ - PESSOA JURIDICA ; PF - PESSOA FISICA',
	`COBRANCA_INSCRICAO` VARCHAR(14) NULL DEFAULT NULL COMMENT 'NUMERO DE INSCRICAO DO SACADO (CNPJ/CPF)',
	`COBRANCA_SACADO` VARCHAR(30) NULL DEFAULT NULL COMMENT 'NOME DO SACADO',
	`COBRANCA_LOGRADOURO` VARCHAR(40) NULL DEFAULT NULL COMMENT 'LOGRADOURO',
	`COBRANCA_BAIRRO` VARCHAR(12) NULL DEFAULT NULL COMMENT 'COBRANÇA - BAIRRO',
	`COBRANCA_CEP` VARCHAR(8) NULL DEFAULT NULL COMMENT 'COBRANÇA - CEP',
	`COBRANCA_CIDADE` VARCHAR(15) NULL DEFAULT NULL COMMENT 'COBRANÇA - CIDADE',
	`COBRANCA_ESTADO` VARCHAR(2) NULL DEFAULT NULL COMMENT 'COBRANÇA - ESTADO',
	`COBRANCA_CONTATO` VARCHAR(15) NULL DEFAULT NULL COMMENT 'COBRANÇA - CONTATO',
	`COBRANCA_TELEFONE` VARCHAR(50) NULL DEFAULT NULL COMMENT 'COBRANÇA - TELEFONE',
	`COBRANCA_EMAIL` VARCHAR(120) NULL DEFAULT NULL COMMENT 'COBRANÇA - E-MAIL',
	
	-- CONTRATO
	`CONTRATO_PERIODO_LOCACAO` INT(11) NULL DEFAULT NULL COMMENT 'CONTRATO - PERIODO DE LOCAÇÃO',
	`CONTRATO_FORMA_PAGAMENTO` VARCHAR(50) NULL DEFAULT NULL COMMENT 'CONTRATO - FORMA DE PAGAMENTO',
	`CONTRATO_FATURAMENTO_DIAS` INT(10) NULL DEFAULT NULL COMMENT 'CONTRATO - DIAS PARA FATURAMENTO',
	`CONTRATO_RETIRADA_AUTOMATICA` INT(11) NULL DEFAULT NULL COMMENT 'CONTRATO - RETIRADA AUTOMATICA',
	`CONTRATO_VCTO_APOS_ENTREGA` INT(11) NULL DEFAULT NULL COMMENT 'CONTRATO - VENCIMENTO APOS A ENTREGA',
	`CONTRATO_VALOR` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'CONTRATO - VALOR',
	`CONTRATO_MULTA_MORA` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'CONTRATO - MULTA DE MORA',
	`CONTRATO_MULTA_DIA` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'CONTRATO - MULTA POR DIA',
	`CONTRATO_NF` TINYINT(1) NULL DEFAULT '0' COMMENT 'CONTRATO - EMISSÃO DE NF',
	`CONTRATO_ISS` TINYINT(1) NULL DEFAULT '0' COMMENT 'CONTRATO - EMISSÃO DE ISS',
	`CONTRATO_CTR` TINYINT(1) NULL DEFAULT '0' COMMENT 'CONTRATO - EMISSÃO DE CTR',

	-- CADASTRO
	`CADASTRO_EMISSAO` DATETIME NULL DEFAULT NULL COMMENT 'RESPONSAVEL PELO REGISTRO - EMISSÃO',
	`CADASTRO_USUARIO` VARCHAR(10) NULL DEFAULT NULL COMMENT 'RESPONSAVEL PELO REGISTRO - USUÁRIO',
	
	-- ULTIMA ALTERAÇÃO
	`SISTEMA_EMISSAO` DATETIME NULL DEFAULT NULL COMMENT 'ULTIMA ALTERAÇÃO DO REGISTRO - EMISSÃO',
	`SISTEMA_USUARIO` VARCHAR(10) NULL DEFAULT NULL COMMENT 'ULTIMA ALTERAÇÃO DO REGISTRO - USUÁRIO',
	
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=15;
