DELIMITER //

CREATE VIEW vw_contatos AS

select 
	cadastros.ID AS ID,
	cadastros.ID_RELACAO AS ID_RELACAO,
	cadastros.CNPJ_CPF AS CNPJ_CPF,	
	cadastros.CONTATO AS CONTATO,
	cadastros.TELEFONE AS TELEFONE,
	cadastros.EMAIL AS EMAIL,
	cadastros.CADASTRO_OBSERVACAO AS OBSERVACAO,
	cadastros.COBRANCA_INSCRICAO AS COBRANCA_INSCRICAO,
	
	concat(cadastros.CONTATO,' - ',cadastros.TELEFONE) AS SOLICITANTE,	
	
	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 

from 
	cadastros 
where 
	(cadastros.REGISTRO_CATEGORIA = _utf8'CONTATO_CLIENTE') order by cadastros.ID desc 
	
DELIMITER ;