DELIMITER //

CREATE VIEW vw_historicos AS

select 
	cadastros.ID AS ID,
	cadastros.ID_RELACAO AS ID_CLIENTE,
	cadastros.CADASTRO_OBSERVACAO AS HISTORICO,
	cadastros.COBRANCA_INSCRICAO AS COBRANCA_INSCRICAO,
	
	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 
from 
	cadastros 
where 
	(cadastros.REGISTRO_CATEGORIA = _utf8'CLIENTE_HISTORICO') order by cadastros.ID desc 
	
DELIMITER ;