DELIMITER //

CREATE VIEW vw_login AS

select 
	cadastros.ID AS ID,
	cadastros.NOME AS NOME,
	cadastros.NUMERO AS SENHA,
	
	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 
from 
cadastros 
where (cadastros.REGISTRO_CATEGORIA = _utf8'USUARIOS') order by cadastros.NOME asc  
	
DELIMITER ;