DELIMITER //

CREATE VIEW vw_obras AS

select 
	cadastros.ID AS ID,
	cadastros.ID_RELACAO AS ID_CLIENTE,
	cadastros.CEP AS CEP,
	cadastros.NUMERO AS NUMERO,
	cadastros.COMPLEMENTO AS COMPLEMENTO,
	cadastros.ENDERECO AS ENDERECO,
	cadastros.BAIRRO AS BAIRRO,
	cadastros.CIDADE AS CIDADE,
	cadastros.ESTADO AS ESTADO,
	cadastros.CONTATO AS CONTATO,
	cadastros.TELEFONE AS TELEFONE,
	cadastros.EMAIL AS EMAIL,
	cadastros.CADASTRO_TIPO AS COBRANCA_TIPO,
	
	cadastros.COBRANCA_INSCRICAO AS COBRANCA_INSCRICAO,
	cadastros.COBRANCA_SACADO AS COBRANCA_SACADO,
	cadastros.COBRANCA_LOGRADOURO AS COBRANCA_LOGRADOURO,
	cadastros.COBRANCA_BAIRRO AS COBRANCA_BAIRRO,
	cadastros.COBRANCA_CEP AS COBRANCA_CEP,
	cadastros.COBRANCA_CIDADE AS COBRANCA_CIDADE,
	cadastros.COBRANCA_ESTADO AS COBRANCA_ESTADO,
	cadastros.COBRANCA_CONTATO AS COBRANCA_CONTATO,
	cadastros.COBRANCA_TELEFONE AS COBRANCA_TELEFONE,
	cadastros.COBRANCA_EMAIL AS COBRANCA_EMAIL,
	
	cadastros.CONTRATO_INICIO AS CONTRATO_INICIO,
	cadastros.CONTRATO_VALOR AS CONTRATO_VALOR,
	cadastros.CONTRATO_NF AS CONTRATO_NF,
	cadastros.CONTRATO_ISS AS CONTRATO_ISS,
	cadastros.CONTRATO_CTR AS CONTRATO_CTR,
	
	cadastros.CONTRATO_FORMA_PAGAMENTO AS CONTRATO_FORMA_PAGAMENTO,
	cadastros.CONTRATO_FATURAMENTO_DIAS AS CONTRATO_FATURAMENTO_DIAS,
	cadastros.CONTRATO_PERIODO_LOCACAO AS CONTRATO_PERIODO_LOCACAO,
	cadastros.CONTRATO_RETIRADA_AUTOMATICA AS CONTRATO_RETIRADA_AUTOMATICA,
	cadastros.CONTRATO_VCTO_APOS_ENTREGA AS CONTRATO_VCTO_APOS_ENTREGA,
	cadastros.CONTRATO_MULTA_MORA AS CONTRATO_MULTA_MORA,
	cadastros.CONTRATO_MULTA_DIA AS CONTRATO_MULTA_DIA,
	
	cadastros.CADASTRO_OBSERVACAO AS CADASTRO_OBSERVACAO,
	
	cadastros.CONTRATO_OBS_LIGACAO AS CONTRATO_OBS_LIGACAO,
	cadastros.CONTRATO_OBS_COLOCA AS CONTRATO_OBS_COLOCA,
	cadastros.CONTRATO_OBS_TROCA AS CONTRATO_OBS_TROCA,
	cadastros.CONTRATO_OBS_RETIRA AS CONTRATO_OBS_RETIRA,
	
	cadastros.REGISTRO_RELACIONAMENTO AS REGISTRO_RELACIONAMENTO,	
	
	concat(cadastros.ENDERECO,' ',cadastros.NUMERO,' - ',cadastros.COMPLEMENTO,' - ',cadastros.BAIRRO) AS OBRA,
		
	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 
	
from 
	cadastros 
where 
	(cadastros.REGISTRO_CATEGORIA = _utf8'CLIENTE_OBRA') order by cadastros.ID desc 
	
DELIMITER ;