DELIMITER //

CREATE VIEW vw_transportadores AS

select 
	cadastros.ID AS ID,

	cadastros.NOME AS NOME,
	cadastros.TELEFONE AS TELEFONE,
	
	cadastros.CADASTRO_TIPO AS TIPO,
	cadastros.CNPJ_CPF AS CPF_CCM,
	cadastros.IE_RG AS LIMPURB,
	
	cadastros.CEP AS CEP,
	cadastros.ENDERECO AS ENDERECO,
	cadastros.NUMERO AS NUMERO,
	cadastros.COMPLEMENTO AS COMPLEMENTO,
	cadastros.BAIRRO AS BAIRRO,
	cadastros.CIDADE AS CIDADE,
	cadastros.ESTADO AS ESTADO,
	
	cadastros.CONTRATO_FORMA_PAGAMENTO AS CONTRATO_FORMA_PAGAMENTO,
	
	cadastros.CONTRATO_FATURAMENTO_DIAS AS CONTRATO_FATURAMENTO_DIAS,	
	cadastros.CONTRATO_PERIODO_LOCACAO AS CONTRATO_PERIODO_LOCACAO,
	cadastros.CONTRATO_RETIRADA_AUTOMATICA AS CONTRATO_RETIRADA_AUTOMATICA,
	cadastros.CONTRATO_VCTO_APOS_ENTREGA AS CONTRATO_VCTO_APOS_ENTREGA,
	
	cadastros.CONTRATO_MULTA_MORA AS CONTRATO_MULTA_MORA,
	cadastros.CONTRATO_MULTA_DIA AS CONTRATO_MULTA_DIA,
	
	cadastros.CONTRATO_NF AS FATURAMENTO_COLOCA,
	cadastros.CONTRATO_ISS AS FATURAMENTO_TROCA,
	cadastros.CONTRATO_CTR AS FATURAMENTO_RETIRA,	
	
	cadastros.CONTRATO_PRECO as PRECO_TIPO,
	cadastros.CONTRATO_VALOR as PRECO_VALOR,	
		
	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 	
	
from 
	cadastros 
where 
	(cadastros.REGISTRO_CATEGORIA = _utf8'ADM_TRANSPORTADOR') order by cadastros.ID desc 
	
DELIMITER ;