CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW vw_cad_funcionarios_cargos AS 
select 
	cadastros.ID AS ID,
	cadastros.CADASTRO_PROPAGANDA AS CARGO,
	
	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 
from 
cadastros 
where (cadastros.REGISTRO_CATEGORIA = _utf8'FUNCIONARIO_CARGO') order by cadastros.ID desc;