CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW vw_dgv_cep AS 
select 
	cadastros.ID AS ID,
	cadastros.ENDERECO AS ENDERECO,
	cadastros.COMPLEMENTO AS COMPLEMENTO,
	cadastros.BAIRRO AS BAIRRO,
	cadastros.CEP AS CEP,
	cadastros.CIDADE AS CIDADE,
	cadastros.ESTADO AS ESTADO,
	cadastros.CONTRATO_VALOR AS CONTRATO_VALOR,

	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 
from 
	cadastros 
where (cadastros.REGISTRO_CATEGORIA = _utf8'UTEIS_CEP') order by cadastros.ID desc;