CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW vw_dgv_veiculos AS 
select 
	cadastros.ID AS ID,
	cadastros.CEP AS PLACA,
	cadastros.NOME AS MODELO,

	cadastros.REGISTRO_CATEGORIA AS REGISTRO_CATEGORIA,
	cadastros.REGISTRO_INSERT_EMISSAO AS REGISTRO_INSERT_EMISSAO,
	cadastros.REGISTRO_INSERT_USUARIO AS REGISTRO_INSERT_USUARIO,
	cadastros.REGISTRO_UPDATE_EMISSAO AS REGISTRO_UPDATE_EMISSAO,
	cadastros.REGISTRO_UPDATE_USUARIO AS REGISTRO_UPDATE_USUARIO 
from 
	cadastros 
where 
(cadastros.CADASTRO_CATEGORIA = _utf8'CAD_VEICULO') order by cadastros.ID desc;