CREATE PROCEDURE sp_ADM_TRANSPORTADOR
(
IN p_ACAO VARCHAR(10),
IN p_ID_TRANSPORTADOR INT,
IN p_NOME VARCHAR(60) ,
IN p_CPF_CCM VARCHAR(14),
IN p_LIMPURB VARCHAR(12),
IN p_CEP VARCHAR(8),
IN p_NUMERO VARCHAR(10),
IN p_COMPLEMENTO VARCHAR(50),
IN p_TELEFONE VARCHAR(50),
IN p_CONTRATO_FORMA_PAGAMENTO VARCHAR(50),
IN p_CONTRATO_FATURAMENTO_DIAS VARCHAR(50),
IN p_CONTRATO_PERIODO_LOCACAO INT,
IN p_CONTRATO_RETIRADA_AUTOMATICA INT,
IN p_CONTRATO_VCTO_APOS_ENTREGA INT,
IN p_CONTRATO_MULTA_MORA INT,
IN p_CONTRATO_MULTA_DIA INT,
IN p_FATURAMENTO_COLOCA INT,
IN p_FATURAMENTO_TROCA INT,
IN p_FATURAMENTO_RETIRA INT,
IN p_PRECO_TIPO TINYINT,
IN p_PRECO_VALOR VARCHAR(50),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_ATERRO
(
IN p_ACAO VARCHAR(10),
IN p_ID_ATERRO INT,
IN p_CADASTRO_TIPO VARCHAR(2),
IN p_NOME_FANTASIA VARCHAR(50),
IN p_NOME VARCHAR(100),
IN p_ENDERECO VARCHAR(255),
IN p_NUMERO VARCHAR(10),
IN p_COMPLEMENTO VARCHAR(50),
IN p_BAIRRO VARCHAR(50),
IN p_CEP VARCHAR(8),
IN p_CIDADE VARCHAR(50),
IN p_ESTADO VARCHAR(2),
IN p_CONTATO VARCHAR(20),
IN p_TELEFONE VARCHAR(100),
IN p_EMAIL VARCHAR(120),
IN p_CNPJ_CPF VARCHAR(14),
IN p_IE_RG VARCHAR(16),
IN p_CADASTRO_STATUS VARCHAR(20),
IN p_CADASTRO_OBSERVACAO VARCHAR(50),
IN p_CONTRATO_VALOR vaRCHAR(50),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_CLIENTE
(
IN p_ACAO VARCHAR(10),
IN p_CADASTRO_TIPO VARCHAR(2),
IN p_CNPJ_CPF VARCHAR(14),
IN p_IE_RG VARCHAR(50),
IN p_NOME VARCHAR(100),
IN p_NOME_FANTASIA VARCHAR(50),
IN p_CEP VARCHAR(8),
IN p_NUMERO VARCHAR(10),
IN p_COMPLEMENTO VARCHAR(50),
IN p_CONTATO VARCHAR(20),
IN p_TELEFONE VARCHAR(100),
IN p_EMAIL VARCHAR(120),
IN p_CADASTRO_OBSERVACAO VARCHAR(50),
IN p_CADASTRO_STATUS VARCHAR(50),
IN p_CADASTRO_STATUS_OBSERVACAO VARCHAR(50),
IN p_CADASTRO_PROPAGANDA VARCHAR(50),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_CLIENTE_CONTATO
(
IN p_CADASTRO VARCHAR(50),
IN p_ACAO VARCHAR(10),
IN p_ID_CONTATO INT,
IN p_ID_RELACAO INT,
IN p_CONTATO_NOME VARCHAR(20),
IN p_CONTATO_TELEFONE VARCHAR(100),
IN p_CONTATO_EMAIL VARCHAR(120),
IN p_CONTATO_OBSERVACAO VARCHAR(100),
IN p_CONTATO_SOLICITANTE TINYINT,
IN p_USUARIO VARCHAR(10),
IN p_CLIENTE_CNPJ_CPF VARCHAR(50)
)

CREATE PROCEDURE sp_CAD_CLIENTE_HISTORICO
(
IN p_ACAO varCHAR(10),
IN p_ID_OBSERVACAO INT,
IN p_CNPJ_CPF VARCHAR(50),
IN p_OBSERVACAO VARCHAR(50),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_CLIENTE_OBRA
(
IN p_ACAO VARCHAR(10),
IN p_CLIENTE_CNPJ_CPF VARCHAR(50),
IN p_ID_OBRA INT,
IN p_CEP VARCHAR(8),
IN p_NUMERO VARCHAR(10),
IN p_COMPLEMENTO VARCHAR(100),
IN p_CONTATO VARCHAR(15),
IN p_TELEFONE VARCHAR(50),
IN p_EMAIL VARCHAR(120),
IN p_COBRANCA_TIPO VARCHAR(2),
IN p_COBRANCA_INSCRICAO VARCHAR(14),
IN p_COBRANCA_SACADO VARCHAR(30),
IN p_COBRANCA_CEP VARCHAR(8),
IN p_COBRANCA_BAIRRO VARCHAR(12),
IN p_COBRANCA_CIDADE VARCHAR(15),
IN p_COBRANCA_ESTADO VARCHAR(2),
IN p_COBRANCA_CONTATO VARCHAR(15),
IN p_COBRANCA_TELEFONE VARCHAR(50),
IN p_COBRANCA_EMAIL VARCHAR(120),
IN p_CONTRATO_INICIO VARCHAR(10),
IN p_CONTRATO_NF TINYINT,
IN p_CONTRATO_ISS TINYINT,
IN p_CONTRATO_CTR TINYINT,
IN p_USUARIO VARCHAR(10),
IN p_CONTRATO_FORMA_PAGAMENTO VARCHAR(50),
IN P_CONTRATO_FATURAMENTO_DIAS VARCHAR(50),
IN p_CONTRATO_VALOR VARCHAR(50),
IN p_CONTRATO_PERIODO_LOCACAO VARCHAR(50),
IN p_CONTRATO_RETIRADA_AUTOMATICA VARCHAR(50),
IN p_CONTRATO_VCTO_APOS_ENTREGA VARCHAR(50),
IN p_CONTRATO_MULTA_MORA VARCHAR(50),
IN p_CONTRATO_MULTA_DIA VARCHAR(50),
IN p_COBRANCA_LOGRADOURO VARCHAR(40),
IN p_CONTRATO_OBSERVACAO VARCHAR(100),
IN p_CONTRATO_OBS_COLOCA VARCHAR(100),
IN p_CONTRATO_OBS_TROCA VARCHAR(100),
IN p_CONTRATO_OBS_RETIRA VARCHAR(100),
IN p_CONTRATO_OBS_GERAL VARCHAR(100)
)

CREATE PROCEDURE sp_CAD_CLIENTE_STATUS
(
IN p_ACAO VARCHAR(10), 
IN p_ID_STATUS INT, 
IN p_OBSERVACAO VARCHAR(50), 
IN p_STATUS VARCHAR(50), 
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_FUNCIONARIO
(
IN p_ACAO VARCHAR(10),
IN p_ID_FUNCIONARIO INT,
IN p_CNPJ_CPF VARCHAR(14),
IN p_IE_RG VARCHAR(50),
IN p_CARGO VARCHAR(50),
IN p_NOME VARCHAR(100),
IN p_CEP VARCHAR(8),
IN p_NUMERO VARCHAR(10),
IN p_COMPLEMENTO VARCHAR(50),
IN p_CONTATO VARCHAR(20),
IN p_TELEFONE VARCHAR(100),
IN p_EMAIL VARCHAR(120),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_FUNCIONARIO_CARGO
(
IN p_ACAO VARCHAR(50),
IN p_ID_CARGO INT,
IN p_CARGO VARCHAR(50),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_CAD_VEICULO
(
IN p_ACAO VARCHAR(10), 
IN p_ID_VEICULO INT, 
IN p_PLACA VARCHAR(8), 
IN p_MODELO VARCHAR(25), 
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_MOV_CONDICOES
(
IN p_ACAO VARCHAR(10),
IN p_ID_CONDICAO INT,
IN p_CONDICAO_PAGAMENTO VARCHAR(50),
IN p_CONDICAO INT,
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_MOV_FLUXO
(
IN p_ACAO VARCHAR(10),
IN p_ID_MOVIMENTO INT,
IN p_MOVIMENTO VARCHAR(50),
IN p_DataDeEmissao VARCHAR(50),
IN p_CONTA VARCHAR(50),
IN p_DataDeVencimento VARCHAR(50),
IN p_ValorOriginal VARCHAR(50),
IN p_DataDePagamento VARCHAR(50),
IN p_ValorFinal VARCHAR(50),
IN p_FormaDePagamento VARCHAR(50),
IN p_Documento VARCHAR(50),
IN p_Observacao VARCHAR(50),
IN p_USUARIO VARCHAR(10)
)

CREATE PROCEDURE sp_MOV_PCONTAS
(
IN p_ACAO VARCHAR(50),
IN p_ID_PLANO INT,
IN p_CONTA VARCHAR(50),
IN p_GRUPO VARCHAR(50),
IN p_FREQUENCIA VARCHAR(50),
IN p_PLANO VARCHAR(50),
IN p_USUARIO VARCHAR(50)
)

CREATE PROCEDURE sp_MOV_PCONTAS_GRUPOS
(
IN p_ACAO VARCHAR(50),
IN p_ID_GRUPO INT,
IN p_GRUPO VARCHAR(50),
IN p_USUARIO VARCHAR(50)
)

CREATE PROCEDURE sp_MOV_TRANSACAO
(
IN p_ACAO VARCHAR(10),
IN p_ID_TRANSACAO INT,
IN p_TRANSACAO VARCHAR(50),
IN p_USUARIO VARCHAR(10)
)

