
SET p_STATUS_CLIENTE				= (SELECT CADASTRO_STATUS FROM vw_cad_clientes WHERE ID = p_ID_CLIENTE);


IF p_ACAO = "INSERT" THEN

ELSEIF p_ACAO = "UPDATE" THEN
	SELECT * FROM CADASTROS;
ELSEIF p_ACAO = "DELETE" THEN
	SELECT * FROM CADASTROS;
END IF; 


BEGIN
	UPDATE vw_servicos_solicitacao
		SET
			SERVICO_STATUS 	= IF(SERVICO_STATUS = TRUE,FALSE,TRUE),
			CAD_USUARIO 		= p_USUARIO,
			CAD_EMISSAO 		= curdate()			
	WHERE
		ID = p_ID_SOLICITACAO;
END

BEGIN
	UPDATE vw_servicos_solicitacao
		SET
			SERVICO_STATUS 	= FALSE,
			CAD_USUARIO 		= p_USUARIO,
			CAD_EMISSAO 		= curdate()			
	WHERE
		ID = p_ID_SOLICITACAO;
END