SELECT 
ID_CLIENTE,ENDERECO,NUMERO,COMPLEMENTO,BAIRRO,CEP,CIDADE,ESTADO,CONTATO,TELEFONE,EMAIL,'CLIENTE_OBRA' 
FROM 
vw_cad_clientes 


SELECT 
COBRANCA_TIPO,COBRANCA_INSCRICAO,COBRANCA_SACADO,COBRANCA_CEP,COBRANCA_LOGRADOURO,COBRANCA_BAIRRO,COBRANCA_CIDADE,COBRANCA_ESTADO,COBRANCA_CONTATO,COBRANCA_TELEFONE,COBRANCA_EMAIL
FROM 
vw_cad_clientes_obras;


SELECT 
CONTRATO_FORMA_PAGAMENTO,CONTRATO_FATURAMENTO_DIAS,CONTRATO_VALOR,CONTRATO_PERIODO_LOCACAO,CONTRATO_RETIRADA_AUTOMATICA,CONTRATO_VCTO_APOS_ENTREGA,CONTRATO_MULTA_MORA,CONTRATO_MULTA_DIA,CONTRATO_INICIO,CONTRATO_NF,CONTRATO_ISS,CONTRATO_CTR
FROM 
vw_cad_clientes_obras;



SELECT 
CONTRATO_PERIODO_LOCACAO,CONTRATO_FORMA_PAGAMENTO,CONTRATO_FATURAMENTO_DIAS,CONTRATO_RETIRADA_AUTOMATICA,CONTRATO_VCTO_APOS_ENTREGA,CONTRATO_MULTA_MORA,CONTRATO_MULTA_DIA
FROM
vw_adm_transportador
LIMIT 1;